### ISSUE TITLE
Redirect wired youtube

### ISSUE THREAD

**Issue by tonton217** [linuxserver/docker-pwndrop#2]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

Force redirect wired youtube

https://www.youtube.com/watch?v=oHg5SJYRHA0
------------------------------

## Expected Behavior

I want to see Pwndrop mainpage

## Current Behavior

Redirect to https://www.youtube.com/watch?v=oHg5SJYRHA0

## Steps to Reproduce

1. this is piece of my docker-compose.yml
```yaml
  pwndrop:
    image: linuxserver/pwndrop
    container_name: pwndrop
    env_file:
      - owner.env
      - tz.env
    volumes:
      - ./pwndrop/config:/config
    ports:
      - 18084:8080
    restart: unless-stopped
```
2. docker-compose up -d
3. http://your-domain:18084

## Environment
**OS: ubuntu 20.04      
**CPU architecture:** x86_64      
**How docker service was installed:**      

docker-compose
